bundler_args: "--without development --path=~/.bundle"
rvm:
- 2.0.0
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
- gem install bundler fog unf
before_script: export PATH=$PATH:/home/travis/.bundle/packer
script: bundle exec thor nmd:validate
notifications:
  hipchat:
    rooms:
      secure: "RIZFLcHmlVNLPlgMgWFCbDp6U18iACvh52b2LySjIuQtNmZaq1nEK5x9+WojM32W+054zeW9SX58JFH1IaJIHulme0hlu6twG6X+nFtrfq1/j0U1RttGRaie+bjgf4XZ9kBd6q6jg/TxwJhYpSdabNRAsLWi9EpIwo/A5HcJpuE="
install: scripts/cached-bundle install --without integration --deployment
env:
  global:
  - PACKER_FILENAME="0.5.1_linux_amd64.zip"
  - secure: Kx+TKkluTArFj8Bcafh4oL2b05iO0r3qwf721pMOn6qrSa6fSgbmCq0eXH51zd7dWuI9ELZ48stQJDw00agoGFgx2fs7skKzGug2UiwSssP0XyZouf3cjcxMTmfG4E0t2MoFdH9RhThC05E5rf05c+nIqmjvEJdZDSgZqhtpHxA=
