rvm:
  - 2.0.0

before_install: wget --no-check-certificate https://dl.bintray.com/mitchellh/packer/0.5.1_linux_amd64.zip && unzip -d packer 0.5.1_linux_amd64.zip
before_script: export PATH=$PATH:$PWD/packer

script: bundle exec thor nmd:validate

notifications:
  hipchat:
    rooms:
      secure: "k+wVQce7mo9qEhG8ko5yU8SH5DTwhoV45zbxVcs+cakZtsBDl9bpb5OUaWFKhygroC6TuPF0qdAn/G3Hs76AFfsOiNPNmmSVvFF2rv95TQvnDk6JfgqsKoVwdEtOJYAVsnb3peOcebuonzy3MfSRN0vFLcx7jNBKyOhwHqCP1yk="
