bundler_args: "--without development --path=vendor/bundle"
rvm:
- 2.0.0
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
- scripts/travis/bundle_install.sh
before_script: export PATH=$PATH:$BUNDLE_PATH/packer
script: bundle exec thor nmd:validate
notifications:
  hipchat:
    rooms:
      secure: RIZFLcHmlVNLPlgMgWFCbDp6U18iACvh52b2LySjIuQtNmZaq1nEK5x9+WojM32W+054zeW9SX58JFH1IaJIHulme0hlu6twG6X+nFtrfq1/j0U1RttGRaie+bjgf4XZ9kBd6q6jg/TxwJhYpSdabNRAsLWi9EpIwo/A5HcJpuE=
install: scripts/cached-bundle install --without integration --deployment
env:
  global:
  - BUNDLE_PATH="/home/travis/vendor/bundle"
  - secure: ZM1TpwYH6cud2/nI9uJiQMZJ8wQZtf5kll0VFJ17wjQPxisKEFFgVJVEDeYN4hBlsqjWg7rFP+7mGfmcAD92gJyjgvImcXSaoJfapsFhEm8IDLmPNRxhuoKZMkabWIfqoU0yg2nPlAawUeJWzcshuJq7Q0a9BdE2/NYkUsIN25w=
