bundler_args: "--without development --path=~/.bundle"
rvm:
- 2.0.0
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
- gem install bundler fog unf
- "./scripts/travis/bundle_install.sh"
- wget --no-check-certificate https://dl.bintray.com/mitchellh/packer/0.5.1_linux_amd64.zip
  && unzip -d packer 0.5.1_linux_amd64.zip
before_script: export PATH=$PATH:$PWD/packer
script: bundle exec thor nmd:validate
notifications:
  hipchat:
    rooms:
      secure: k+wVQce7mo9qEhG8ko5yU8SH5DTwhoV45zbxVcs+cakZtsBDl9bpb5OUaWFKhygroC6TuPF0qdAn/G3Hs76AFfsOiNPNmmSVvFF2rv95TQvnDk6JfgqsKoVwdEtOJYAVsnb3peOcebuonzy3MfSRN0vFLcx7jNBKyOhwHqCP1yk=
env:
  global:
  - BUNDLE_ARCHIVE="nmdpacker"
  - AWS_S3_REGION="us-east-1"
  - AWS_S3_BUCKET="nmd-cache"
  - PACKER_FILENAME="0.5.1_linux_amd64.zip"
  - secure: Kx+TKkluTArFj8Bcafh4oL2b05iO0r3qwf721pMOn6qrSa6fSgbmCq0eXH51zd7dWuI9ELZ48stQJDw00agoGFgx2fs7skKzGug2UiwSssP0XyZouf3cjcxMTmfG4E0t2MoFdH9RhThC05E5rf05c+nIqmjvEJdZDSgZqhtpHxA=
after_script:
- ruby scripts/travis/bundle_cache.rb
