rvm:
  - 2.0.0

before_install: wget --no-check-certificate https://dl.bintray.com/mitchellh/packer/0.5.1_linux_amd64.zip && unzip -d packer 0.5.1_linux_amd64.zip
before_script: export PATH=$PATH:$PWD/packer

script: bundle exec thor nmd:validate

notifications:
  hipchat:
    rooms:
      secure: "PZE3vv48b+vEZiCXW/pSwWMUGZ6WZqikI9UcgfLGCR3YDLOVL/ClcUdGMyl1OtkFPdvbJ1TJ1DJnEygJTyrp1FKLDxFbUkL1cVsLKkw7DPnhA1kCDMAxcSCXVisqK9FphWIoFxjeGzG9KClKiioWzv7a8tbeJDXXS9Bh723afsg="
