bundler_args: "--without development --path=~/.bundle"
rvm:
- 2.0.0
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
- gem install bundler fog unf
- ruby scripts/travis/bundle_cache.rb
before_script: export PATH=$PATH:/home/travis/.bundle/packer
script: bundle exec thor nmd:validate
notifications:
  hipchat:
    rooms:
      secure: RFtV7R9DA3AAujrRnRiEj/ZGWEqn3SFkEFKZZDQEuEEVDobJlkd8MdxSUkEWI/6BXgaAnM138qoq85JckY0QkTAxv2cAYx79OYQGYQReOqRdPEjSAl2gU27c0Umg9EG8lMHr51hYaP7SNs521kpFPujKRfY7irtlxGTvSrPBlC4=
env:
  global:
  - AWS_S3_REGION="us-east-1"
  - AWS_S3_BUCKET="nmd-cache"
  - PACKER_FILENAME="0.5.1_linux_amd64.zip"
  - secure: Kx+TKkluTArFj8Bcafh4oL2b05iO0r3qwf721pMOn6qrSa6fSgbmCq0eXH51zd7dWuI9ELZ48stQJDw00agoGFgx2fs7skKzGug2UiwSssP0XyZouf3cjcxMTmfG4E0t2MoFdH9RhThC05E5rf05c+nIqmjvEJdZDSgZqhtpHxA=
after_script:
- ruby scripts/travis/bundle_cache.rb after
