bundler_args: "--without development --path=/home/travis/build/newmediadenver/nmdpacker/vendor/bundle"
rvm:
- 2.0.0
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
- scripts/travis/bundle_install.sh
before_script: export PATH=$PATH:$BUNDLE_PATH/packer
script: bundle exec thor nmd:validate
notifications:
  hipchat:
    rooms:
      secure: RIZFLcHmlVNLPlgMgWFCbDp6U18iACvh52b2LySjIuQtNmZaq1nEK5x9+WojM32W+054zeW9SX58JFH1IaJIHulme0hlu6twG6X+nFtrfq1/j0U1RttGRaie+bjgf4XZ9kBd6q6jg/TxwJhYpSdabNRAsLWi9EpIwo/A5HcJpuE=
install: scripts/cached-bundle install --without integration --deployment --path vendor/bundle
env:
  global:
  - BUNDLE_PATH="/home/travis/build/newmediadenver/nmdpacker/vendor/bundle"
  - secure: ePuE+Ng7oUTYTL13iFpz3s6uairF7UNJP8yf4/HhlPn4XKwR0tTtFn3CbRZ0MN4iQTfWZrwLlikESNpIVbBrU3yoHIw4bx3uUe9CnT2FTVisph7gFnHiqaIUbHpn49XVM2hl13Q3fkWuVs+Il9Tj1uNBMKzhnVApl3w6INaUagc=
